# Generated by Django 5.0.1 on 2024-01-27 14:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = ()
    operations = ()
