# Generated by Django 5.0.1 on 2024-01-28 17:47

import petstagram.photos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_alter_photo_tagged_pets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(blank=True, upload_to='', validators=[petstagram.photos.validators.validate_image_less_han_5mb]),
        ),
    ]
