# Generated by Django 5.0.1 on 2024-02-22 23:26

import django.core.validators
import petstagram.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='first_name',
            field=models.CharField(max_length=2, validators=[django.core.validators.MinLengthValidator(2), petstagram.core.validators.validate_only_letters]),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='last_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), petstagram.core.validators.validate_only_letters]),
        ),
    ]
