# Generated by Django 5.0.1 on 2024-01-28 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = ()

    operations = ()

