# Generated by Django 5.0.1 on 2024-01-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_pet_slug_alter_pet_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='slug',
            field=models.SlugField(blank=True, unique=True), #this line is changed
            #migrations only connects with poletata
        ),
    ]
